name: Manual Strategy (Ibrahimovic)

on:
  workflow_dispatch:

run-name: Manual Strategy Run

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install requests
    - name: Run strategy
      env:
        GITHUB_TOKEN: ${{ secrets.GAME_TOKEN }}
      run: python strategy.py


